# project definitions
topnav_title: Illinois Cogcomp NLP
homepage_title: Illinois Cogcomp NLP
site_title: Illinois Cogcomp NLP
company_name: CogComp
footer_image_location: /common_images/logo.png
# variables
